theme: jekyll-theme-minimal
title: Geoffrey Meier
description: >
  Welcome to Geoffrey Meier's portfolio webpage!
  <br><br>
  <a href="https://www.linkedin.com/in/geoffrey-meier/">View my LinkedIn Profile</a>
logo: "/121.jpg"

